### ISSUE TITLE
Prevent split screen

### ISSUE THREAD

**Issue by johnsoliman** [eyeson-team/js-docs#1]
Hi,

is it somehow possible to prevent a split screen for the remoteStream if someone joined the room, where you can see both users at once. For our application it is only possible that 2 users join the room, therefor we might want to position the screens in another way.

**Comment by unused** [comment]
Hello, can you please describe how your custom layout should look like or provide some mockup?

**Comment by unused** [comment]
Thank you for the mockup. We offer some participants layout adaption for the video, you can test it on the regular eyeson webgui or [accounts.eyeson.team](https://accounts.eyeson.team). With using a [single stream](https://help.eyeson.team/faq-s/eyeson-technology-explained/what-is-single-stream-technology) every participants has the same video pictures, needless to show the secondary stream.

**Comment by johnsoliman** [comment]
And how do I use a single stream with the javascript library? I can't find any option about layout in the documentation...

**Comment by unused** [comment]
As described in the [help center](https://help.eyeson.team/faq-s/eyeson-technology-explained/what-is-single-stream-technology) the eyson service provides a single stream for you, the JavaScript library offers this at the connection. This is the remoteStream received.

We did not put the layout into the documentation (yet) as it is a very rare use-case and mostly used when streaming webinars. However if you plan to implement a feature similar to the web-gui - set participants to specific positions - let me know and I'll collect the details for you. Note that this won't allow to create the view like you described in the mockup either.

**Comment by johnsoliman** [comment]
I can see that you use the following event. I just need a documentation what is needed here. Which layoutTypes are possible and what do I have to provide for parameter users. Is users optional or mandatory?

eyeson.send({
        type: "update_stream",
	layoutType: "one",
	users: {}
});

Thanks in advance.

**Comment by unused** [comment]
You don't have to take care for any stream updates when changing the layout. As in the eyeson web gui you can use `auto`, `one`, `two`, or `four` as layoutType and you have to provide the id of a user to be set for the specific position using an empty string for an empty position. The correct structure is as follows...

```javascript
eyeson.send({
  type: 'set_layout',
  params: {
    layoutType: 'two',
    users: ['', '<user-id>'],
  },
});
```

**Comment by johnsoliman** [comment]
Is it the same user id I used when generating the room link? I tried it with the user ID specified when making the room, but it doesn't seem to work.

Room created with users:
{id: UserA, name: UserAName},
{id: UserB, name: UserBName}

Event sent when UserAName visits the gui:
eyeson.send({
  type: 'set_layout',
  params: {
    layoutType: 'one',
    users: ['UserB'],
  },
});

**Comment by unused** [comment]
The user-id is the identification you receive from the API. Note: It doesn't matter which client sets the layout, every participant will see the same video [as mentioned before](https://github.com/eyeson-team/js-docs/issues/1#issuecomment-414583610).
