### ISSUE TITLE
API source on GitHub

### ISSUE THREAD

**Issue by ian-luca** [eyeson-team/js-docs#11]
Would it be possible to publish the source of the JS api onto GitHub?

As there are no typings and there arent any end-to-end integration examples in the documentation it can be really hard figuring out how the api is meant to be used. Moreover it would open up to possible community contributors

**Comment by unused** [comment]
For any server-side communication please refer to the [API documentation](https://eyeson-team.github.io/api/api-reference/). The [JS documentation](https://eyeson-team.github.io/js-docs/) includes all helpers needed to setup any custom UI, but there is no end-to-end integration done on client-side. If you have any specific question that is not covered in the documentation do not hesitate to leave a message!
