### ISSUE TITLE
Can users' audio / video be muted centrally

### ISSUE THREAD

**Issue by PHPGuus** [eyeson-team/js-docs#12]
Hi there,

not so much an issue, as it is a feature request or feature question.

I see in the JS documentation, that each user could mute his / her audio or video feed. Is there a possibility for a central user to do this as well?

I see that I can call eyeson.send({ type: "change_stream", options: { audio: false, video: true } }) in order to mute the audio stream of the current user, however it would be nice, if I could also submit a user ID  (obtained through fetch_room or add_user) in order to provide a central panel for the meeting organizer to mute somebody's audio / video stream.

Is this maybe already possible?

Best regards,
Guus

**Comment by unused** [comment]
Hello, thank you for the feedback. We currently have no plan to implement such a feature but I'm happy to bring it to the table. However as it is client-side you have full control to easily build it within a custom UI. A handy tool in this case it the websocket connection, that you can utilize the chat (e.g. using slash commands) to transfer/broadcast such a command and interact on the client selected. Best wishes!

**Comment by PHPGuus** [comment]
Oh perfect, yes of course I wasn't thinking outside of the box ;-)

**Comment by PHPGuus** [comment]
Hi there,

further on this, am I correct in assuming that in order to mute a user's own microphone, I need to `eyeson.send({type: "change_stream", options: { audio: false, video: true }});`? Or is that the wrong event to send to eyeson?

(Similar for one's own video, but instead of sending `video: true`, I'll send `video: false`.)

Thanks for letting me know!

**Comment by PHPGuus** [comment]
Hi there,

I see that I receive a "stream_update" with a stream and a localStream. Based on that I grabbed the video element, and simply did:

```
                            video.src = event.stream;
                            video.play();
```

But that did not seem to actually mute the microphone (because I can still see the microphone icon on the podium when I make a sound...).

Can you help, please? ;-)

Thanks and best regards,
Guus

**Comment by opusonline** [comment]
Hi, nice to meet you.
In order to avoid issues, you can use another strategy to toggle microphone, see https://github.com/eyeson-team/api/issues/42#issuecomment-639411181.
Hope this helps!
Best regards!
