### ISSUE TITLE
How to end a conference for all participants

### ISSUE THREAD

**Issue by PHPGuus** [eyeson-team/js-docs#14]
Hi there,

what calls would one need to make to the API (via PHP or JS) in order to close a conference for all participants, please?

Best regards,
Guus

**Comment by unused** [comment]
Hi, you can send a request using HTTP method DELETE on the room endpoint, like `DELETE /rooms/:identifier # force to stop a running meeting` see the [API documentation in the eyeson Room section](https://eyeson-team.github.io/api/api-reference/#eyeson-room). Best wishes!
