### ISSUE TITLE
Browsing away from and back to video conference page

### ISSUE THREAD

**Issue by PHPGuus** [eyeson-team/js-docs#15]
Hi there,

I found that if a user browses away from the page that shows the video conference, that user's video and audio stream are still active (which is a Good Thing(TM)!). How could I detect that the user is still an active user and reconnect the video stream correctly when the user browses back to the video conference page? Just setting up a new participant for the room obviously joins the same person for a second time...

Thank you for providing me with some clues as to how to do this ;-)

Best regards,
Guus

**Comment by unused** [comment]
Hello, I'm not sure if I got you correctly but the connection is closed on leaving the web UI and you can simply start over again. You can test the behavior in the default web UI which does not keep any session information (as it is statically hosted) and does setup the meeting with the access key only. So no need to join a meeting again (server-side) but reuse the access key. However this has a downside: The meeting will expire after a short period of time and the user will not be able to rejoin. If you keep your UI in a dynamic environment (e.g. PHP) you can also simply rejoin (server-side) your participant using a unique room identifier `id` and user identifier `user[id]` combination, see the [API documentation for further details](https://eyeson-team.github.io/api/api-reference/#eyeson-room).

How you handle this depends a lot on your use case, I hope you can figure out the best strategy with the information given, if not please do not hesitate to let me know :)
