### ISSUE TITLE
Eyeson Flow

### ISSUE THREAD

**Issue by ian-luca** [eyeson-team/js-docs#16]
My Scenario:
In the backend I create a room and return the `access_key` to the frontend so I can join the person that started the room with the js-APIs `eyeson.start(accessKey)`.
All other participants of my room are generated on demand in the backend and as with the room creation the `access_key` for the guest user is returned to the guest users frontend application.

My Questions:
1. Say a guest users computer crashes - how do I rejoin the presentation? The provided `access_key` will be invalid by the time  the user is ready rejoin. Is there a way of refreshing the `access_key` or do I have to create a new guest user for the presentation every time? And if I have to create them every time how to remove the old one from the room?
2. How to correctly end a session (frontend)? I tried it with `eyeson.destroy()` but when I start a new room, close it with `eyeson.destroy()` afterwards and start a new room I get an "you have to terminate the old session first" error.
3. When I do not end the session on purpose but for example the browser crashes eyeson would reconnect to the session when I open the page again - how do I reconnect the video stream when no `accept` event is received
4. is there something wrong with the `REGISTER sip:integrations.visocon.com SIP/2.0` and directly after that `SIP/2.0 401 Unauthorized` loggings? can I ignore them or does the Unauthorized Response tell me there is something not configured the way it should be

**Comment by unused** [comment]
The `access_key` is valid for a single meeting, if there is someone presenting any other participant can rejoin anytime. If there are no participants in a meeting it will expire and the access keys are no longer valid. If you are unsure if a meeting is running and you need to rejoin simply join users [using a unique room identifier](https://eyeson-team.github.io/api/api-reference/#eyeson-room) so you ensure they will participate in the same meeting.

You can destroy a running meeting by using [HTTP method DELETE on the room endpoint](https://eyeson-team.github.io/api/api-reference/#eyeson-room) with either identifier (authenticated) or access key.

If you can join a session properly please ignore any SIP message received.

Please do not hesitate to leave a comment if you have any further questions!
