### ISSUE TITLE
stream video after joining with video disabled

### ISSUE THREAD

**Issue by ian-luca** [eyeson-team/js-docs#19]
When I join a conference, with `eyeson.start(accessKey, { video: false, audio: false })`, I\`m not able to activate video streaming afterwards.

I\`ve tried it with these three options:
1. Using the `StreamHelpers`, as is necessary with audio
`StreamHelpsers.enableCamera(eyeson.session.localStream)`

2. Using the `change_stream` event, as poorly documented in this repository
`eyeson.send({ type: 'change_stream',  options: { video: true })`

3. Building a new stream using `MediaStreamBuilder`
`eyeson.session.setStream(await new MediaStreamBuilder({ video: true, audio: true }))`

Am I missing something, or is one of the above the "official" way of enabling video

I havn\`t had any problems with `StreamHelpers.enableCamera(...)`/`StreamHelpers.disableCamera(...)` when the stream was joined with `{ video: true, ... }` options

**Comment by opusonline** [comment]
Hello @ian-luca,

thank you so much for your feedback!

I had a closer look and noticed a mistake on the documentation for `change_stream` event. [It is now updated](https://eyeson-team.github.io/js-docs/events/#change_stream).

The correct way using it is:
```js
eyeson.send({ type: 'change_stream', video: true, audio: true })
```
You can also see a working demo in the [React-web-gui-example](https://github.com/eyeson-team/react-web-gui-example/blob/master/src/App.js#L60).

Best regards,
Stefan
