### ISSUE TITLE
eyeson start is not a function in js library

### ISSUE THREAD

**Issue by alamgira** [eyeson-team/js-docs#21]
I am trying to handle all eyeson event using basic javascript. I have installed eyeson js using npm and referred to it in html file like this
<script type="text/javascript" src="./node_modules/eyeson/dist/eyeson.js"></script> and alsow tried creating a bundle using browerify, same issue. 

When I call eyeson.start(), I am getting an error 
Uncaught TypeError: eyeson.start is not a function

**Comment by unused** [comment]
If you are including the package like this you'll have to use `window.eyeson` and it should work fine. However I'd recommend to use a modern bundler like [webpack](https://webpack.js.org/) to setup such a project that helps a lot managing resources. Best wishes!
