### ISSUE TITLE
streaming to youtube

### ISSUE THREAD

**Issue by alamgira** [eyeson-team/js-docs#25]
Hello 
Video is not streaming to youtube. I have created a broadcast using eyeson php and received true in response in the server side. It says "Upcoming" in youtube platform. 
In addition, after creating broadcast via server, i made a send call using javascript

```
eyeson.send(
{
 type: 'start_youtube',
  broadcastId,
  streamUrl
	}
);

```

I received 406 error with this message
```{"error":"Platform youtube is already in use. You can only have one stream per platform."}```

Youtube still says scheduled and upcoming. 
![image](https://user-images.githubusercontent.com/3598597/100020058-2d727500-2dad-11eb-90de-41b083734fa8.png)

how do we initiate youtube live streaming

**Comment by unused** [comment]
>  In addition, after creating broadcast via server, i made a send call using javascript.
No need to send another request.

Please ensure the meeting is ready and use platform `generic` when sending RTMP details. The platform `youtube` and `facebook` are reserved for a client-side approach that requires interaction with 3rd party APIs - I'll update the [documentation on this](https://eyeson-team.github.io/api/api-reference/#broadcast) as soon as possible.

**Comment by alamgira** [comment]
hello @unused ,
I am using eyeson php library and using generic as platform. 

`$broadcast = $eyeson->broadcast($access_key, "generic", "YT_RTMPS_LINK");`

I have had similar issues when I used ffmpeg. I had to start streaming and then i had to make a request to youtube to transition the video state . When we call broadcast at eyeson, does it start streaming? As per youtube documentation, we can only change the state after streaming started.

**Comment by unused** [comment]
Can you please provide a very short description of what you are trying to achieve and what's your issue with eyeson. As far as I understand you want to start a RTMP broadcast without having a stream, which does not make much sense to me. Additionally any meeting will expire after some time if no participants join so I'd recommend to join a participant, then start an RTMP stream. If you're having any troubles with RTMP you can check the behaviour in the default web UI e.g. starting a meeting from [accounts.eyeson.team](https://accounts.eyeson.team/).

**Comment by alamgira** [comment]
Hello @unused ,
This are the cases that we are trying to solve
1) I am trying to broadcast to rtmp with just me in the room
2) Broadcast to rtmp if i have a participant in the room

**Comment by unused** [comment]
If I got you right both use cases are the same: A meeting with one participant that has joined. Providing the RTMP credentials immediately broadcasts the stream to your selected provider. I suggest to test the RTMP feature using the web gui to ensure you got valid credentials. We do not know on any current issues with this feature and it is widely used. Please do not hesitate to leave a comment if you still experience any problem. Best wishes!
