### ISSUE TITLE
Share Screen using javascript

### ISSUE THREAD

**Issue by alamgira** [eyeson-team/js-docs#26]
How do i  share screen using javascript library.

**Comment by unused** [comment]
Hi, you can use `eyeson.send({ type: 'start_screen_capture', audio: true, screenStream: null, screen: true })` to start a a built-in screenshare session and `eyeson.send({ type: 'stop_presenting' })` to stop. See the [react web ui example](https://github.com/eyeson-team/react-web-gui-example/blob/master/src/App.js#L68) that implements this feature. If you need more control over the screen stream (e.g. you want to merge it with another stream) we recommend to use the [web screen capture api](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture) to handle capture control. Best wishes!
