### ISSUE TITLE
Extract Data / Reporting

### ISSUE THREAD

**Issue by codingyourlife** [eyeson-team/js-docs#27]
Hi! I'm curious about the reporting aspect of your platform.

We need to extract data about calls started via the api
- Total call duration of our api key via an api call
- Call duration after the call
- Total call duration somehow per room
- Ideally a batch call for several room keys
- Maybe also amount of participants would be helpful

Is there anything about this in the documentation or if not could you add it? We need some kind of reporting.

Thanks!

**Comment by unused** [comment]
Hi! You can setup a Webhook to receive Meeting events and record the duration on demand. As participants are created through your platform it's best to keep track of them there. If you want to collect information about connect/disconnect during a running meeting you might want to do so in a custom UI. We currently do not provide endpoints to gather statistics but I'm happy to forward your request to do so. Please do not hesitate to leave a comment if you have any further questions on this.
