### ISSUE TITLE
Compile fails when Eyeson JS Library imported in Angular 11 app

### ISSUE THREAD

**Issue by koezukar** [eyeson-team/js-docs#28]
Hi,
I'm developing web app using Angular 11.

I installed Eyeson JS library using npm and imported it in the component named “meeting” in my Angular 11 app.

installation: 
`npm i --save eyeson`

usage:
`import eyeson from 'eyeson'`
(./src/app/meeting/meeting.component.ts)

Then an error message was displayed on my VSCode and I can’t compile my app:

`Could not find a declaration file for module 'eyeson'. 'c:/Users/koezu/Documents/test-environment/test-eyeson/eyeson-test-app/node_modules/eyeson/dist/eyeson.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/eyeson` if it exists or add a new declaration (.d.ts) file containing `declare module 'eyeson';`

Here’s my app repository:
https://github.com/koezukar/eyeson-test-app

What can I do to compile my app and to embed meeting in my Angular app?

**Comment by opusonline** [comment]
Hi,
thanks for trying eyeson!
It seems like this issue is pretty common and related to Angular's usage of TypeScript.
Here's a good description of how you can solve this:
https://amandeepkochhar.medium.com/typescript-error-could-not-find-a-declaration-file-for-module-xyz-dfbe6e45c2bd
Hope that helps!
Please do not hesitate to leave a comment if you still experience any problem. Best wishes!
Best regards, Stefan

**Comment by koezukar** [comment]
Thanks for reply.
If we put the following at our tsconfig.json, then every methods implemented in the SDK will be interpreted as one returning Any variable.
`"noImplicitAny": false` 
Therefore we cannot use VSCode code assist.
Are you going to provide d.ts file in the coming version?

**Comment by opusonline** [comment]
Hello.
I'm sorry to hear, that updating the config doesn't work for you.
I couldn't find any easy method to create such `.d.ts` files right away. It's currently not planned but I'll definitely keep an eye on it and will let you know as soon as we have any updates on this.
If you could find a solution, please let me know!
Best wishes! Stefan
