### ISSUE TITLE
Screen sharing doesn't end

### ISSUE THREAD

**Issue by astropoint** [eyeson-team/js-docs#29]
Hi,

I'm using 
eyeson.default.send({ type: 'start_screen_capture', audio: myaudio, screenStream: null, screen: true });
to start a screen share succesfully, and that works fine.  Trying to stop it is less succesful though.

eyeson.default.send({ type: 'stop_presenting' });
doesn't seem to do anything, I would have expected it to switch off the screen share and switch back to the webcams of people in the room, or would something else need to be run?  Looking at the console window it clearly posts the command through,
EventHandler::send {type: "stop_presenting", _src: "client"}
EventHandler::send {type: "presentation_ended"}
both end up attached to Logger.js

eyeson.default.send({ type: 'start_stream', video: true, audio: true, screen: false});
seems to work as a stopgap, but that seems to get some of the clients into a bit of a weird loop unable to connect their webcams back to the chat until somebody else joins/leaves or refreshes the page

As a 'possibly' related note, I am having to use eyeson.default instead of just eyeson for all of the calls. I saw another example at https://github.com/eyeson-team/js-docs/issues/23 that initiated the eyeson call via
var eyesonModule = window.eyeson;
var eyeson = eyesonModule.default;
which presumably does the same thing longer term?  Does eyeson have to be initiated separately somehow?

For the record here I am not using react, just linking in the eyeson.js file directly, using the version directly from an npm install

**Comment by unused** [comment]
No need to use React (or any other web framework like Vue, Svelte, etc.), you can use the JavaScript package any way you want. However we strongly recommend to use a modern dependency manager like webpack to load eyeson and it might not be possible for us to help with custom implementations that we cannot reproduce.

Can you please check if you have the same troubles using the [react example](https://eyeson-team.github.io/react-web-gui-example/) which [uses `stop_presenting` to end the screen capture](https://github.com/eyeson-team/react-web-gui-example/blob/master/src/App.js#L75)?

**Comment by astropoint** [comment]
Short answer is no but I can't even get video working on that let alone screen share, so I am presumably doing something wrong somewhere. It seems to run, accept the meeting key, but doesn't get any further.  That said, I don't doubt that the function will work there if I were to somehow getting it up and running, but short of rewriting the entire site as is from scratch into a react framework I don't think it would do alot of good.

I've copied below as simplified a version of the page as I can, that still gives the error.  It's a combination of php and javascript (I wasn't if it was even possible to directly generate the tokens via javascript so had to mix and match a bit)
```

<?php
use EyesonTeam\Eyeson\Eyeson;
include("vendor/autoload.php");
$options = array();
	$options['show_label'] = false;
	$options['layout_available'] = true;
	$options['reaction_available'] = false;
	$options['guest_token_available'] = false;
	$options['broadcast_available'] = false;
	$options['broadcast_available'] = false;
	
	$eyeson = new Eyeson("KEY");
	
	$room = $eyeson->join("Joe Bloggs", "QWERTYUOP", $options);
	
	$url = $room->getUrl(); 
	$token = explode("?", $url)[1];
?>
<!DOCTYPE html>
<html lang='en'>
   <head>
      <title>Video</title>
      <meta name='viewport' content='width=device-width, initial-scale=1'>
      <link href='node_modules/bootstrap/dist/css/bootstrap.min.css' rel='stylesheet'>
      <link href='node_modules/bootstrap-select/dist/css/bootstrap-select.min.css' rel='stylesheet'>
      <script src='node_modules/jquery/dist/jquery.min.js'></script>
      <script src='node_modules/eyeson/dist/eyeson.js'></script>
   </head>
   <body id='page-top'>
      <div id='container_wide'>
      <h1>Video</h1>
      <div class='row'>
         <div class='col-8 text-center'>
						<input type='button' onclick='enableScreenShare()' id='sharescreen' value='Enable screen share' class='btn btn-primary'  />
						<input type='button' onclick='disableScreenShare()' id='unsharescreen' value='Stop sharing screen' class='btn btn-primary hide' />
          </div>
      </div>
      <h4>Public</h4>
      <div class='row'>
         <div class='col-8'>
            <video style='max-height:600px;width:100%' id='eyesonvideo' >Video loading, please wait...</video>
         </div>
      </div>
      <script src='node_modules/bootstrap/dist/js/bootstrap.bundle.min.js'></script>
      
      <script>
         $(document).ready(function(){
         
					 eyeson.default.onEvent(event => {
							if (event.type !== "accept") {
								return;
							}
							let video = document.querySelector("video");
							video.srcObject = event.remoteStream;
							video.play();
					 });
					 eyeson.default.start("<?php echo $token; ?>");
					});
					
					
					 function enableScreenShare(){
							eyeson.default.send({ type: 'start_screen_capture', audio: true, screenStream: null, screen: true });
						}

						function disableScreenShare(){
							eyeson.default.send({ type: 'stop_presenting' });
						}

      </script>
   </body>
</html>

```

The composer.json file is as follows
```

{
    "require": {
        "eyeson/eyeson-php": "^1.4"
    }
}
```

and package.json for download of the javascript package via npm

```
{
  "name": "test",
  "version": "0.0.1",
  "description": "",
  "main": "javascripts/index.js",
  "author": "",
  "license": "UNLICENSED",
  "dependencies": {
    "bootstrap": "^4.6.0",
    "eyeson": "^1.6.1",
    "jquery": "^3.5.1"
  }
}

```

**Comment by unused** [comment]
There is no issue related to eyeson but it seems to me your HTML document is broken. I've tested your code with a slightly adapted version and it works fine.

```html
<!DOCTYPE html>
<html lang="en">
   <head>
     <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Video</title>
      <link href="node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
      <link href="node_modules/bootstrap-select/dist/css/bootstrap-select.min.css" rel="stylesheet">
      <script src="node_modules/jquery/dist/jquery.min.js"></script>
      <script src="node_modules/eyeson/dist/eyeson.js"></script>
   </head>
   <body id="page-top">
      <div id="container_wide">
      <h1>Video</h1>
      <div class="row">
         <div class="col-8 text-center">
           <input type="button" onclick="enableScreenShare()" id="sharescreen" value="Enable screen share" class="btn btn-primary"  />
           <input type="button" onclick="disableScreenShare()" id="unsharescreen" value="Stop sharing screen" class="btn btn-primary hide" />
          </div>
      </div>
      <h4>Public</h4>
      <div class="row">
         <div class="col-8">
            <video style="max-height:600px;width:100%" id="eyesonvideo" >Video loading, please wait...</video>
         </div>
      </div>

      <script src="node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

      <script>
         $(document).ready(function(){
           eyeson.default.onEvent(event => {
             if (event.type === 'presentation_ended') {
               eyeson.send({ type: 'start_stream', audio: true, video: true });
               return;
             }
             if (event.type !== "accept") {
               return;
             }
             let video = document.querySelector("video");
             video.srcObject = event.remoteStream;
             video.play();
           });
           eyeson.default.start("<?php echo $token ?>");
         });


        function enableScreenShare(){
          eyeson.default.send({ type: "start_screen_capture", audio: true, screenStream: null, screen: true });
        }

        function disableScreenShare(){
          eyeson.default.send({ type: "stop_presenting" });
        }
      </script>
   </body>
</html>
```

Please double check the HTML document is valid and in doubt test using the samples provided. For better handling we recommend to use modern tools like [Webpack](https://webpack.js.org/) to handle JavaScript modules. Best wishes!

**Comment by astropoint** [comment]
Thanks, yes it was adding
if (event.type === 'presentation_ended') {
               eyeson.send({ type: 'start_stream', audio: true, video: true });
               return;
             }
That sorted it, I didn't realise that was a requirement along with the 
eyeson.default.send({ type: "stop_presenting" });
command.

(just for the benefit of anybody else who may get stuck at the same specific point as me)
