### ISSUE TITLE
One on one video call

### ISSUE THREAD

**Issue by pnordhus** [eyeson-team/js-docs#3]
I would like to create a meeting with two participants who can see each other (a 1:1 call). However, when using the JS API to connect to a room the remote stream I get contains both the local and the remote video side by side.

When using the eyeson Web GUI, it works as expected (i.e. fusion mode is disabled) with two participants. Each user can only see the other user in the remote stream.

How can I get the same result as the Web GUI using the JS API?

**Comment by wpp** [comment]
Hi,

This is totally my fault @pnordhus. We've changed how the (JS) clients can declare their stream capabilities (fusion mode) but haven't updated the library accordingly. I'll try to get this done ASAP and let you know when you can expect an update later today.

Sorry for the troubles!

**Comment by wpp** [comment]
We're expecting to release a new version by the end of the week. Hope that works for you.

**Comment by pnordhus** [comment]
That's good to hear, thank you!

**Comment by wpp** [comment]
Hi,

just published version 1.2.0. You shouldn't have to change anything regrading SFU behaviour, it should _just work_ (you won't see the participants side by side).

I've tested this with our example react application here: https://github.com/eyeson-team/react-web-gui-example. That project might be helpful if you have further questions/issues/feature-requests.

Cheers

**Comment by pnordhus** [comment]
Awesome! Now it works as expected, thanks for the quick update!
