### ISSUE TITLE
stream_update should mention that either local or stream receives the update

### ISSUE THREAD

**Issue by codingyourlife** [eyeson-team/js-docs#32]
https://eyeson-team.github.io/js-docs/events/#stream_update seems behave wrong if you update stream AND local. you need to check if one of those has data, right?

We did it like this:
```
if (event.type === "stream_update") {
	const local = event.localStream;
	if (local) {
		setState((prevState) => ({
			...prevState,
			local: local,
		}));
	}

	const stream = event.stream;
	if (stream) {
		setState((prevState) => ({
			...prevState,
			stream: stream,
		}));
	}
	return;
}
```

When we tried updating them both in one step it was not working correctly.

Would be great if the documentation would mention this.

**Comment by unused** [comment]
Thank you for the feedback, the documentation mentions to provide a local stream or a remote stream. We'll discuss this internally and update the documentation accordingly. Do not hesitate to leave a comment if you have any further questions!
