### ISSUE TITLE
Set on DeviceManager does not state that it wants a deviceId

### ISSUE THREAD

**Issue by codingyourlife** [eyeson-team/js-docs#33]
From reading [https://eyeson-team.github.io/js-docs/utilities/#device-manager](https://eyeson-team.github.io/js-docs/utilities/#device-manager) someone could assume that for e.g.
`deviceManager.setAudioInput(microphone); // switch microphone`
you should pass in the microphone object. I checked the code from bitbucket and saw that the parameter is called deviceId and that's what is being accepted. Otherwise you run into an OverconstrainedError and such things.

Improvement suggestion:
`deviceManager.setAudioInput(microphone.deviceId); // switch microphone`
-> and same for the other devices

**Comment by unused** [comment]
Thank you for the input, we have update the parameter names accordingly.
