### ISSUE TITLE
What are those ice_failed events?

### ISSUE THREAD

**Issue by codingyourlife** [eyeson-team/js-docs#36]
In a call with the team the image froze several times and those freezing moments correlated to error logs of {"type":"error","name":"ice_failed"} event.
I cannot find anything about the specific errors that can occur in your documentation under [https://eyeson-team.github.io/js-docs/events/#error-handling-and-notifications](https://eyeson-team.github.io/js-docs/events/#error-handling-and-notifications). 

I had a look at the codebase and you reference this bug in the appropriate section [https://bugs.chromium.org/p/chromium/issues/detail?id=982793&q=ice%20failed&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified](https://bugs.chromium.org/p/chromium/issues/detail?id=982793&q=ice%20failed&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)

So were these connection problems? Do they need to be handled better? The page needed to be refreshed... What happened exactly? Can it be simulated somehow (like disconnecting from wifi etc.)?

**Comment by opusonline** [comment]
Hi!

Every meeting participant creates a peer connection to the conference server to exchange audio/video media streams.
Whenever connection quality goes bad, the RTCPeerConnection iceConnectionState will change accordingly. We are looking for "disconnected/connected" and "failed".

As you already have seen in the codebase, a "disconnect" state will trigger the "ice_disconnected" warning. If the connection was not able to reconnect after a certain amount of time, the error "ice_failed" is triggered. And if the connection state is "failed", you will see the error "ice_failed" immediately.

We suggest to react the following way:
- "ice_disconnected" is just a warning, so you may want to show a note to the users
- "ice_failed" means that audio/video is disrupted. Try to restart the eyeson session to establish a new connection.

Please do not hesitate to leave a comment if you have any further questions on this!
Best regards.
