### ISSUE TITLE
eyeson Chrome Extension link is down

### ISSUE THREAD

**Issue by codingyourlife** [eyeson-team/js-docs#37]
here https://github.com/eyeson-team/js-docs/blob/main/content/screen-capture/index.md you mention the link to the eyeson chrome extension which points here https://chrome.google.com/webstore/detail/eyeson/bbdcikainjamgglhllfjbkeibiiclnck and the link is down

**Comment by unused** [comment]
Looks like there is a removed content still in the repository, however it is not in the [JavaScript Documentation](https://eyeson-team.github.io/js-docs/) as extensions are no longer needed to use screenshare in modern browsers. There is a [post in our techblog](https://techblog.eyeson.team/posts/screen-cam/) that might help you dealing with screen capturing. We'll remove the outdated document soon.
