### ISSUE TITLE
Exit meeting with `bye`

### ISSUE THREAD

**Issue by mohamad-zbib** [eyeson-team/js-docs#38]
when my network is not stable the meeting is exited with `reason = "bye"`,

how can i handle it?

**Comment by unused** [comment]
You can find a list of errors and warnings that may be received and can be handled in the [error handling and notifications section of the documentation](https://eyeson-team.github.io/js-docs/events/#error-handling-and-notifications). Do not hesitate to leave a comment if you have any further questions on this!
