### ISSUE TITLE
Implement eyeson JS into asp.net MVC

### ISSUE THREAD

**Issue by venkatvenugopal** [eyeson-team/js-docs#39]
Hi,

I am trying to implement the eyeson js video calling into my existing asp.net mvc application. can someone guide me in this?

I already contacted Ekaterina Melnikova from sales team. Based on her response only I am creating this ticket.

Regards,
Venkat

**Comment by unused** [comment]
Hi Venkat, nice to meet you. We'll be happy to guide you and help to adapt it to your needs. 
Did you check the [API documentation](https://eyeson-team.github.io/api/getting-started/) to join a user to a meeting? You only need to call this when your user is ready to join, no need to call anything beforehand, we ensure there is always a meeting ready for you. This is a single HTTP request.
From there you can quickstart using the eyeson default web UI, simple forward the user to the URL located at ".links.gui" in the JSON response. This is a good first step to get comfortable with how it works and you can then start to build your own interface from there using the eyeson JavaScript package and the access-key from the JSON response. I guess you are using some kind of JavaScript framework in your application. Can you let us know which one so we might provide some examples? Let me know if you have any troubles with the first step, don't mind to comment anytime if you have any question!
