### ISSUE TITLE
how to show the controls

### ISSUE THREAD

**Issue by khaledkamara** [eyeson-team/js-docs#4]
i tried the eyes on js.lib
in jquery it works fine, but with out any control only the video of the caller and the caller only see my video 
no controls are there only my name and the video
how can i show the controls (mute/ share screen /record/ chat )

![eyeson](https://user-images.githubusercontent.com/47121454/77555374-da63bd80-6ebf-11ea-9de8-d32cc3b284db.PNG)

**Comment by unused** [comment]
You can either use the prepare GUI that is also linkend in the API response out-of-the-box or create your own custom web interface. The library provides you with a lot of helpers, however we do not provide explicit controls. Please have  a look on the [sample project](https://github.com/eyeson-team/react-web-gui-example) we provide to get an idea of how to implement controls and all other features you want to integrate in your custom UI. Best wishes!
