### ISSUE TITLE
Example of how to change video/audio/mic.

### ISSUE THREAD

**Issue by natschz** [eyeson-team/js-docs#40]
Could you maybe provide a full example of how to change the microphone/camera/output?

Currently I'm using the devicemanager, which does not appear to work consistently. Also for the output device it seams to not work at all.

I tried to set the devices with the device manager and also even tried to send the 'start_stream' event.

So it would be aswesome if you could maybe provide a example of how to change audio/video/mic.

**Comment by unused** [comment]
There is a [usage example present using React](https://github.com/eyeson-team/react-web-gui-example/blob/main/src/Preview.js), can you please provide any details what the problems are that you're facing? Thank you in advance!

**Comment by natschz** [comment]
Yes I saw the example, I tried to use as much as possbile form it, but since its 'old react' 😅 and the code is kind of scattered, it was not so clear what was needed and what not.

Sorry currently I don't have the time to create a isolated example, but our component looks like the one below.

What I noticed that after cam the cam changes, one has to call the 'stream_start' event event tough the stream is running and it appears to update the cam then.

```jsx
eyeson.send({
  type: 'start_stream',
  audio: audio,
  video: video
});
```

But for the mic I tried chaning the mic and output device and it seamingly just works randomly. So maybe you can provide some information, what needs to be done after changing the device, besides calling the start_stream event (if this is even needed or appropriate) and also what to do for the mic and speaker setting to be applied conistently and correct!

I look forward to feedback! 🙂


```jsx

  const getSelectedDeviceId = (stream, type) => {
    try {
      const tracks = stream[`get${type}Tracks`]();
      if (tracks.length > 0) {
        const settings = tracks[0].getSettings();
        return settings.deviceId;
      }
    } catch (error) {
      console.error(error);
    }
    return null;
  };

  const Settings = ({}) => {
    const [cameras, setCameras] = useState()
    const [microphones, setMicrophones] = useState()
    const [speakers, setSpeakers] = useState()
    const [constraints, setConstraints] = useState()
    const [options, setOptions] = useState()
  
    const [stream, setStream] = useState()
    const [camera, setCamera] = useState("")
    const [microphone, setMicrophone] = useState("")
    const [speaker, setSpeaker] = useState("")
  
    const [microphoneMeter, setMicrophoneMeter] = useState("")
  
    const deviceManager = useMemo(() => new DeviceManager, [])
    useEffect(() => {
      if (stream) {
        const soundMeter = new SoundMeter();
  
        soundMeter
          .connectToSource(stream)
          .onUpdate(event => {
            if (event.error) {
              console.error(event.error);
            }
            setMicrophoneMeter(event.value)
          })
  
        return () => {
          setMicrophoneMeter(0)
          soundMeter.stop();
        }
      }
    }, [stream, setMicrophoneMeter])
  
    useEffect(() => {
      if (deviceManager) {
        setCameras(deviceManager.cameras)
        setMicrophones(deviceManager.microphones)
        setSpeakers(deviceManager.speakers)
        setConstraints(deviceManager.constraints)
        setSpeaker(deviceManager.sinkId)
  
        deviceManager.onChange(event => {
  
          if (event.cameras) {
            setCameras(event.cameras);
          }
  
          if (event.microphones) {
            setMicrophones(event.microphones);
          }
  
          if (event.speakers) {
            setSpeakers(event.speakers);
          }
  
          if (event.constraints) {
            setConstraints(event.constraints);
          }
  
          if (event.options) {
            setOptions(event.options);
          }
  
          if (event.stream) {
            setStream(event.stream)
            const microphoneId = getSelectedDeviceId(event.stream, 'Audio');
            const cameraId = getSelectedDeviceId(event.stream, 'Video');
            setMicrophone(microphoneId);
            setCamera(cameraId);
          }
  
          if (event.sinkId) {
            setSpeaker(event.sinkId)
          }
        });
  
        deviceManager.start()
  
        return () => {
          deviceManager.stop()
        }
      }
    }, [deviceManager])
  
    const handleSelectVideoInput = (event) => {
      if (deviceManager) {
        deviceManager.setVideoInput(event.target.value)
        deviceManager.storeConstraints()
      }
    };
  
    const handleSelectAudioInput = (event) => {
      if (deviceManager) {
        deviceManager.setAudioInput(event.target.value)
        deviceManager.storeConstraints()
      }
    };
  
    const handleSelectAudioOutput = (event) => {
      if (deviceManager) {
        deviceManager.setAudioOutput(event.target.value)
        deviceManager.storeConstraints()
        setSpeaker(event.target.value)
      }
    };
  
    return <div>
      <FormControl style={{width: "100%"}} disabled={!options?.video}>
        <InputLabel id="video-input-select-label">Camera</InputLabel>
        <Select
          labelId="video-input-select-label"
          id="video-input-select"
          value={camera || ""}
          onChange={handleSelectVideoInput}
        >
          {(cameras || []).map(camera => {
            return <MenuItem key={camera.deviceId} value={camera.deviceId}>{camera.label}</MenuItem>
          })}
        </Select>
      </FormControl>
  
      <FormControl style={{width: "100%", marginTop: "1.25rem"}} disabled={!options?.audio}>
        <InputLabel id="audio-input-select-label">Microphone</InputLabel>
        <Select
          labelId="audio-input-select-label"
          id="audio-input-select"
          value={microphone || ""}
          onChange={handleSelectAudioInput}
        >
          {(microphones || []).map(microphone => {
            return <MenuItem key={microphone.deviceId} value={microphone.deviceId}>{microphone.label}</MenuItem>
          })}
        </Select>
      </FormControl>
      <LinearProgress variant="determinate" value={microphoneMeter}/>
  
      <FormControl style={{width: "100%", marginTop: "1.25rem"}} disabled={!options?.audio}>
        <InputLabel id="audio-output-select-label">Speaker</InputLabel>
        <Select
          labelId="audio-output-select-label"
          id="audio-output-select"
          value={speaker || ""}
          onChange={handleSelectAudioOutput}
        >
          {(speakers || []).map(speaker => {
            return <MenuItem key={speaker.deviceId} value={speaker.deviceId}>{speaker.label}</MenuItem>
          })}
        </Select>
      </FormControl>
    </div>
  }

```

**Comment by opusonline** [comment]
Hi!
As far as I can see, your code snippet refers to device settings during an ongoing meeting and not the device setup before the meeting.
The DeviceManager is holding its own separate media stream. So in order to see and hear the settings, you need to plug this stream into a separate media element (See SettingsDialog [Line 58](https://github.com/eyeson-team/react-web-gui-example/blob/main/src/SettingsDialog.js#L58) and [Line 84](https://github.com/eyeson-team/react-web-gui-example/blob/main/src/SettingsDialog.js#L84)).
This allows to change and preview the cam/mic/speaker without disturbing the current meeting. When you want to apply the new selected devices, you have to trigger the "start_stream" event as you've already mentioned. If you want to dismiss the changes, you simply don't need to trigger the "start_stream" event…
Again, the "start_stream" event is only to apply the settings that you've done using the DeviceManager to the meeting's media stream.
Best regards!
Do not hesitate to leave a comment if you have any further questions on this!

**Comment by opusonline** [comment]
For the audio output, we currently have no demo. But it works like this:
At first, you need `FeatureDetector.canChangeAudioOutput()` to check if audio output is supported in the current browser.
To get the stored audio output device id, you can use `const sinkId = await DeviceManager.getSinkId();`. The sink ID can be applied using `mediaElement.setSinkId(sinkId)`, where `mediaElement` is an HTMLVideoElement or HTMLAudioElement.

**Comment by natschz** [comment]
Hello @opusonline, thank you very much so far!
For us we don't really need to "preview" the settings, we just want to apply them directly.

Setting the sink, seams to do the trick for the output device, the input device seams to just work, and for the cam, on my android phone, I have the issue, that I can't change the cam. Which probably is because the cam won't be applied by the device manager? Also after closing the settings and reopening them, all settings are disabled, which is because of the options from the device manager event (which more or less implemented like your example).

Do you have any further input regarding this?

Thank you in advance!

**Comment by opusonline** [comment]
Hi!

Ok, what I see so far is, the cam change is working:
> What I noticed that after cam the cam changes, one has to call the 'stream_start' event event tough the stream is running and it appears to update the cam then.

and now the audio output is also working:
> Setting the sink, seams to do the trick for the output device

Now you still have troubles with the mic
> But for the mic I tried chaning the mic and output device and it seamingly just works randomly.

and the cam on Android:
> and for the cam, on my android phone, I have the issue, that I can't change the cam.

Since cam change and audio output is working, the mic should also have no problem. You need to use the DeviceManager. It always works like this: selecting the device and store the change using for example `deviceManager.setVideoInput(deviceId)` and then `deviceManager.storeConstraints()`. When constraints are stored, the "start_stream" event will start a new stream with the latest devices.

Please make sure to also check for an error object in the deviceManager's "onChange" event (`if (event.error) {...}`). If a device is not working, it should not be used.

I also suggest to check your android device with our Quick test: https://app.eyeson.team/quicktest/.

Best regards!

**Comment by natschz** [comment]
Most of the things seam to work as of now. 

Thank you for the tip with the event error, this throws a "NotReadableError: Could not start video source", do you have some further insides what that means and/or what can be done to avoid it?

Kind regards!

**Comment by opusonline** [comment]
Hi!

This is an error that is thrown by the browser and it usually means there is another app using your camera which prevents the current page from accessing the camera at the same time.

In this case, we show the following error message to our users:
"Make sure your camera or microphone aren't being used by another program. You might also have to reload the page or restart your browser."

Best regards!
