### ISSUE TITLE
2 participants - show their names

### ISSUE THREAD

**Issue by vahan1107** [eyeson-team/js-docs#41]
Hello !
I have integrated eyeson with VUE3. Everything works fine.

But one question: how to show members names when only 2 members have joined?
Are there any settings when creating a room or something else?

Thank you in advance,
Vahan

**Comment by opusonline** [comment]
Hello Vahan!

Thanks for asking!

If the meeting is started with option `sfu_mode=ptp` (which is the default), then each of the 2 participants will receive the unmodified video stream of the other participant, hence no names are shown on the video.
I suggest to set `options[sfu_mode]=disabled` [1] when you start a meeting. This way, you will always receive the generated "SingleStream" which also includes the names.

Do not hesitate to leave a comment if you have any further questions on this.
Best regards!

[1] https://eyeson-team.github.io/api/api-reference/#eyeson-room

**Comment by vahan1107** [comment]
Hello, thanks for suggestion, it works fine!
