### ISSUE TITLE
Firefox - getting session_failed event

### ISSUE THREAD

**Issue by vahan1107** [eyeson-team/js-docs#43]
Hi,

On Laptop, Firefox (PC), I'm getting these events:
1. {"type": "connection": connectionStatus": "ready"}
2. {"type": "broadcasts_update", "broadcasts": []}
3. {"type": "disconnect"}
4. {"type": "error", "name": "session_failed", "code": "TypeError"}
5. {"type": "disconnect"}

But on chrome it's ok.
What does the 4th event mean and how to solve it?

**Comment by opusonline** [comment]
Hello Vahan,

this looks like a bug somewhere in the starting process. Do you see any more details in the logs?

Please try using the GUI (`links.gui` in [API response](https://eyeson-team.github.io/api/api-reference/#eyeson-room)) or the [example GUI](https://eyeson-team.github.io/react-web-gui-example/) to double-check if the error still occurs in Firefox.

Thanks for your help!

**Comment by opusonline** [comment]
@vahan1107 Do you have any updates on this? Is it working with the GUI or the Example GUI with Firefox?

**Comment by vahan1107** [comment]
hi @opusonline ,

Not yet, I will check it today.

Thank you!

**Comment by vahan1107** [comment]
hi @opusonline ,

we have tested it with our problematic device. Here is the info of the device:
device: Redmi Note 11 Pro 5G with Android 12 and MIUI Global v13.0.6
browser on the device: Firefox: 114.1.0

The problem is that users can't hear and see from another devices when using this device.

Thanks in advance.

**Comment by opusonline** [comment]
Hello @vahan1107,
thanks for your answer, but now I'm confused.
Your initial message was "On Laptop, Firefox (PC), …" and now you're talking about a mobile device.
Is the issue `{"type": "error", "name": "session_failed", "code": "TypeError"}` still existing on Laptop Firefox with our prebuild GUI or the example GUI?
Thanks!

**Comment by vahan1107** [comment]
The only problem I see in the GUI is just the one I described.
I'll let you know if there are problems, as long as that's all I can tell you.
Thank you.

**Comment by vahan1107** [comment]
I can't get `{"type": "error", "name": "session_failed", "code": "TypeError"}` again in my page to check it in your GUI.

**Comment by opusonline** [comment]
@vahan1107 
if I understand correctly, the issue "Firefox - getting session_failed event" does not occur in our GUI?
That means, the error happens due to an issue in your implementation. Please have a closer look into our example GUI https://github.com/eyeson-team/react-web-gui-example.
Regarding the issue on a mobile device, please create a new ticket if you need further help. Thanks in advance!
Best regards, Stefan
