### ISSUE TITLE
Audio issue in React application

### ISSUE THREAD

**Issue by mariomtzrn** [eyeson-team/js-docs#45]
Hi,

I'm trying to integrate the Eyeson library into a React application designed to function as a broadcast platform with one host and multiple audience members. While I've successfully implemented functionalities to initialize the stream as a host and join as an audience member, I've encountered an issue with audio specifically when joining as an audience member.

Even after disabling the microphone both before and during the audience member session join, audio from the microphone seems to be active in the stream and it appears as being used in the browser tab. I have tried:

- Disabling the audio and video in the **eyeson.start()** function:
`eyeson.onEvent(handleEvent);`
`eyeson.start(token, {
  video: false,
  audio: false,
});`
- Disabling audio and video access using DeviceManager after joining the session:
`deviceManager.updateWithOptions({
  video: false,
  audio: false,
});`
`deviceManager.storeConstraints();`
- Disabling audio and video using StreamHelpers in the **accept** event:
`StreamHelpers.toggleAudio(event.localStream, false);`
`StreamHelpers.toggleCamera(event.localStream, false);`

Unfortunately, these attempts haven't resolved the problem.

**Comment by opusonline** [comment]
Hello Mario,
thanks for reaching out to us!
The reason for this behaviour is that Eyeson meetings are specified for the meeting use-case and so we've made microphone access required. You can mute it, but the microphone is still accessed all the time.

Luckily, there's a solution for your use-case. EyesonJS offers "[Custom Media Stream](https://docs.eyeson.com/blog/external-stream)" which allows you to avoid microphone access and use a programmed MediaStream instead.

Here's a quick snippet that demonstrates how to create a programmed audio-only Media Stream and how it can be used with EyesonJS.
```js
const createAudioStream = async () => {
    let stream = null;
    try {
        if (typeof window.MediaStreamTrackGenerator === 'function') {
            const track = new MediaStreamTrackGenerator({ kind: 'audio' });
            stream = new MediaStream([track]);
        } else {
            const ac = new (window.AudioContext || window.webkitAudioContext)();
            stream = ac.createMediaStreamDestination().stream;
            await ac.close();
        }
    } catch (error) {
        console.error(error);
    }
    if (stream) {
        stream.getAudioTracks()[0].enabled = false;
        return stream;
    }
    return null;
};

const start = async () => {
    const stream = await createAudioStream();
    eyeson.start(<access_key>, { stream });
};
```

Hope this helps!
Best regards, Stefan

Do not hesitate to leave a comment if you have any further questions on this!
