### ISSUE TITLE
Error: eyeson.onEvent is not a function

### ISSUE THREAD

**Issue by maxou0789** [eyeson-team/js-docs#5]
Hello,
Even the eyeson.js file is loaded successfully, I'm having the following error in the console (from the example file too):

```
Uncaught TypeError: eyeson.onEvent is not a function
    at index.html:20
```

**Comment by unused** [comment]
Hi, I'm not sure what you mean by the `eyeson.js` file is loaded successfully. Can you please give some detail on how you included the library in your project. Did you use a package manager like npm or yarn?

**Comment by maxou0789** [comment]
Hi, thanks for your answer, I used npm and add the library to my project's javascript but I got the error I mentioned previously. Then I opened the example file of the library (examples/index.html) and I saw the same error, am I missing something?

**Comment by maxou0789** [comment]
Hi, it actually works using eyeson.default.onEvent, sorry for the disturbance.
