### ISSUE TITLE
Create a room through js

### ISSUE THREAD

**Issue by Adityaraj1711** [eyeson-team/js-docs#6]
Can I create a room using JS?
I have an online educational site and I wanted to use eyeson in it. All I want is to create a room using my backend only that will generate a link and any student with the link could join the classroom.

In short, A faculty can create a room using my website which would be internally using your API's that will generate the joining link.
I read your documentation and I am not sure if there's such a way to integrate with my python and angular webapp?

**Comment by unused** [comment]
You can start a meeting with any programming language, please find details in the [API documentation](https://eyeson-team.github.io/api/getting-started/#start-and-join-eyeson-room). You do not have to generate a link upfront but redirect your users on-the-fly. You can also set an exit-url to ensure your user will return to your platform afterwards. Joining a room should not be handled on client-side as for sure you will expose your API key this way, which should kept secret. Let me know if you have any additional questions.
