### ISSUE TITLE
Screen capture and video simultaneously

### ISSUE THREAD

**Issue by h8hjoshi** [eyeson-team/js-docs#7]
Hi, When I started the screen capture session via the JS library, it stopped the camera, and I noticed that there's an empty gray block overlayed on the shared screen (maybe due to the disabled camera?). I was looking for a way to share the camera stream and the shared screen/tab/application window, is it possible to do so?

version: 1.4.2
I started the screen capture session using:
```
eyeson.send({
    type: 'start_screen_capture', 
    audio: true, 
    screenStream: stream, //the captured stream
    screen: true
});
```

<img width="1665" alt="screen-capture-session" src="https://user-images.githubusercontent.com/1982287/82116137-be3b1900-97aa-11ea-9173-0120df387b46.png">

**Comment by unused** [comment]
Hi there, sorry for the late reply. You can share screen and video by mixing them using a [HTML canvas](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API) element. Another approach is to send another stream (connect a second participant) during presentation, this will show the screens side-by-side. Both methods require you to [start screen capturing](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture) yourself. Let me know if you have any further questions on this.

Regarding the screenshot: It looks like you are using some fixed width-height for your video element which will work fine for the single stream you receive however cannot be filled by the captured screen as its ratio depends on the screen resolution.
