### ISSUE TITLE
Guest user joining room issue

### ISSUE THREAD

**Issue by maxou0789** [eyeson-team/js-docs#8]
**Hello,**
I am trying to make a guest user joining a created room but after my script execute the following code: `eyeson.default.join({ audio: true, video: true });`

I get the following error: `status_code: 403, reason_phrase: "Forbidden"`
and the following response: `{type: "error", name: "session_failed"}`

**Thanks for your help**

**Comment by unused** [comment]
Hi, did you [create a new user using the guest token](https://eyeson-team.github.io/api/api-reference/#user-and-guest-user)? After receiving the response you can use this user as any other participant.

**Comment by maxou0789** [comment]
Hi, Ok I understand my mistake now, I was trying to use the access_key to connect the guest user, it's working fine now, thanks.
